import { Poppins, Roboto } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600','700','800','900'],
  subsets: ["latin"],
})

const roboto = Roboto({
  variable: '--font-roboto',
  weight: ['100', '200', '300', '400', '500', '600','700','800','900'],
  subsets: ["latin"],
})


export const metadata = {
  title: "Viganium",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
